#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'motortest','console_scripts','simple_publisher'
__requires__ = 'motortest'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('motortest', 'console_scripts', 'simple_publisher')()
    )
